[project]
name = "mesh-proposal-template"
authors = ["mesh-dev-team"]
description = "A decentralized proposal management system"
telemetry = false
requirements = []
[contracts.mesh-proposal]
path = "contracts/mesh-proposal.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
